# ==============================================
# Configuration Section
# ==============================================
model_name_or_path: <Your path to Gemma-2-9B-IT model>
ref_model: <Your path to Gemma-2-9B-IT model>
output_dir: <Your output directory path>
dataset_mixer:
  "<Your path to Gemma-2-9B-IT-UltraFeedback-GPT-4o>": 1.0

# ==============================================
# The settings below do not need to be modified
# ==============================================

chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] | trim + '\n\n' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{% for message in messages %}{% if loop.index0 == 0 %}{% set content = system_message + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + content | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"

# Data training arguments
dataset_splits:
  - train
preprocessing_num_workers: 12

# UniDPOTrainer arguments
learning_rate: 8.0e-7
pref_loss: uni_dpo
beta: 10.0
uni_dpo_qual_eta: 0.7
uni_dpo_tau_ref: 0.8
uni_dpo_perf_gamma: 3.0
uni_dpo_nll_lambda: 0.001
uni_dpo_tau_good: 3.2

use_ref_model: True
dpo_length_norm: True
seed: 42
warmup_ratio: 0.1
hub_model_id: Gemma2-9B-IT-Uni-DPO
run_name: Gemma2-9B-IT-Uni-DPO

torch_dtype: null
attn_implementation: eager
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
per_device_train_batch_size: 1
per_device_eval_batch_size: 3
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 20
